Description: >
  Capstone ekscluster stack.
  
Parameters:
  WorkflowID:
    Description: Unique identifier.
    Type: String

Resources:
  EksCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Sub capstone-${WorkflowID}
      Version: "1.20"
      RoleArn: arn:aws:iam::724333931337:role/myEKSClusterRole
      ResourcesVpcConfig: 
        SecurityGroupIds:
          - sg-0e6883e6b4d2f9647
        SubnetIds:
          - subnet-0846925453ea8acd5
          - subnet-012c9754debe69322
        EndpointPublicAccess: true
      Tags: 
        - Key: Name
          Value: !Sub capstone-${WorkflowID}
  
  EKSNodegroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      AmiType: AL2_x86_64
      CapacityType: ON_DEMAND
      DiskSize: 20
      ClusterName: !Ref EksCluster
      NodeRole: arn:aws:iam::724333931337:role/myEKSWorkerNodeRole
      RemoteAccess:
        Ec2SshKey: udapeople
      ScalingConfig:
        MinSize: 2
        DesiredSize: 2
        MaxSize: 2
      Subnets:
        - subnet-0846925453ea8acd5
        - subnet-012c9754debe69322

Outputs:
  WorkflowID:
    Value: !Sub ${WorkflowID}
    Description: WorkflowID of the stack
    Export:
      Name: WorkflowID