version: 2.1

# commands:
#   destroy-environment:
#     description: Destroy cloudformation stacks given a workflow ID.
#     steps:
#       - run:
#           name:
#           when: on_fail
#           command: |

jobs:
  build-app:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - restore_cache:
         keys: [app-build]
      - run:
         name: Install dependencies
         command: |
           sudo apt-get update
           sudo apt-get install -y nginx --no-install-recommends
      - run:
         name: copy project files
         command: |
            sudo cp ./config/nginx.conf /etc/nginx/nginx.conf
            sudo cp -r ./www /www
      - run:
         name: build app
         command: |
           sudo service nginx start
      - run:
         name: test app
         command: |
           curl http://localhost:80/
      - save_cache:
         paths: [node_modules]
         key: app-build
         
  lint-app:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
         name: install dependencies
         command: |
            pip install hadolintw
            alias hadolint=hadolintw
      - run:
         name: lint on app
         command: |
            hadolintw ./Dockerfile --ignore DL3020
    

workflows:
  default:
    jobs:
      - build-app
      - lint-app:
          requires: [build-app]