version: 2.1

# commands:
#   destroy-environment:
#     description: Destroy cloudformation stacks given a workflow ID.
#     steps:
#       - run:
#           name:
#           when: on_fail
#           command: |

jobs:
  build-app:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - restore_cache:
         keys: [app-build]
      - run:
         name: Install dependencies
         command: |
           sudo apt-get update
           sudo apt-get install -y nginx --no-install-recommends
      - run:
         name: build app
         command: |
           sudo service nginx start
      - save_cache:
         paths: [node_modules]
         key: app-build

workflows:
  default:
    jobs:
      - build-app