version: 2.1

# commands:
#   destroy-environment:
#     description: Destroy cloudformation stacks given a workflow ID.
#     steps:
#       - run:
#           name:
#           when: on_fail
#           command: |

jobs:
  build-app:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - restore_cache:
         keys: [app-build]
      - run:
         name: Install dependencies
         command: |
           sudo apt-get update
           sudo apt-get install -y nginx --no-install-recommends
      - run:
         name: copy project files
         command: |
            sudo cp ./config/nginx.conf /etc/nginx/nginx.conf
            sudo cp -r ./www /www
      - run:
         name: build app
         command: |
           sudo service nginx start
      - run:
         name: test app
         command: |
           curl http://localhost:80/
      - save_cache:
         paths: [node_modules]
         key: app-build
         
  lint-app:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
         name: install dependencies
         command: |
            docker pull hadolint/hadolint
      - run:
         name: lint on app
         command: |
            docker run --rm --interactive hadolint/hadolint < Dockerfile
            
  build-docker-image:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - run:
         name: install curl
         command: |
            apk add --update curl
      - setup_remote_docker
      - run:
         name: build docker image
         command: |
            docker build --tag=capstone .
            docker image ls
            docker image inspect capstone
      - run:
         name: run docker image
         command: |
            docker run --detach --publish=80:80 --name=captsone capstone
      - persist_to_workspace:
          root: /var/lib/docker/overlay2
          paths:
            - .
            
  export-docker-image:
    docker:
      - image: docker:stable
    steps:
      - attach_workspace:
          at: /var/lib/docker
      - run:
         name: push to dockerhub
         command: |
            docker login -u balinkrish2000
            docker tag capstone balinkrish2000/udacityapi:capstone
            docker push balinkrish2000/udacityapi:capstone
            
workflows:
  default:
    jobs:
      - build-app
      - lint-app
      - build-docker-image:
          requires: [build-app, lint-app]
      - export-docker-image:
          requires: [build-docker-image]